// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250428081822_BaslangicVerileriniEkle")]
    partial class BaslangicVerileriniEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Güzel Bir Telefon",
                            ImageUrl = "Image1.jpg",
                            IsActive = true,
                            Name = "Iphone 15",
                            Price = 100m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "İdeal Bir Telefon",
                            ImageUrl = "Image1.jpg",
                            IsActive = true,
                            Name = "Iphone 15SE",
                            Price = 80m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gelişmiş Bir Telefon",
                            ImageUrl = "Image1.jpg",
                            IsActive = true,
                            Name = "Iphone 16",
                            Price = 150m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ust Düzey Bir Telefon",
                            ImageUrl = "Image1.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro",
                            Price = 200m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "En iyi Telefon",
                            ImageUrl = "Image1.jpg",
                            IsActive = true,
                            Name = "Iphone 16 Pro Max",
                            Price = 200m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
